apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
  namespace: canary
  labels:
    app: podinfo
spec:
  selector:
    matchLabels:
      app: podinfo

  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: podinfo
    spec:
      containers:
      - name: podinfod
        image: quay.io/stefanprodan/podinfo:1.7.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9898
        command:
        - ./podinfo
        - --port=9898
        # - --random-error=true
