apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: capdemo
  namespace: test
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: capdemo-deployment
  service:
    port: 80
  analysis:
    interval: 10s
    threshold: 5
    stepWeight: 5
    maxWeight: 100
    metrics:
    - name: request-success-rate
      thresholdRange:
        min: 99
      interval: 1m
    - name: request-duration
      thresholdRange:
        max: 500
      interval: 1m

