---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: load
  namespace: test
spec:
  selector:
    matchLabels:
      app: load
  replicas: 1
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: load
    spec:
      containers:
      - image: buoyantio/slow_cooker:1.2.0
        name: slow-cooker
        env:
          - name: QPS
            value: "100"
          - name: CONCURRENCY
            value: "1"
        command: ["/bin/sh", "-c"]
        args:
          - |-
            slow_cooker -qps ${QPS} -concurrency ${CONCURRENCY} http://capdemo:80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: capdemo-deployment
  namespace: test
spec:
  selector:
    matchLabels:
      app: capdemo
  replicas: 2 
  template:
    metadata:
      labels:
        app: capdemo
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
      - name: nginx
        image: inklin/capdemo
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: capdemo
  namespace: test
  labels:
    app.kubernetes.io/name: loadtester
    app.kubernetes.io/instance: flagger
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: capdemo
---
